# Importação dos dados

In [1]:
import pandas as pd

DATA_PATH = '../data/'
file_name = 'hour.csv'

df = pd.read_csv(DATA_PATH+file_name, sep=',')

df.shape

(17379, 17)

In [2]:
df.head(1)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16

# Verificação dos tipos de dados

In [3]:
df.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

# Verifica valores duplicados

In [4]:
# verifica se existe valores duplicados

df.duplicated().sum()

np.int64(0)

In [5]:
for column in df.columns:
    # ^ inicio da string
    # $ fim da string
    # \s identifica espaços
    # * especifica que o replace será aplicado independente da quantidade de espaços
    print(f'{column}: {df[column].replace(r'^\s*$', pd.NA, regex=True).isna().sum()}')

instant: 0
dteday: 0
season: 0
yr: 0
mnth: 0
hr: 0
holiday: 0
weekday: 0
workingday: 0
weathersit: 0
temp: 0
atemp: 0
hum: 0
windspeed: 0
casual: 0
registered: 0
cnt: 0

# Verifica os valores unicos de cada coluna

In [6]:
# Verifica se os valores fazem sentido para a coluna
for column in df.drop(columns=['instant', 'dteday']).columns:
    print(f'{column}: {df[column].unique()}')

season: [1 2 3 4]
yr: [0 1]
mnth: [ 1  2  3  4  5  6  7  8  9 10 11 12]
hr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
holiday: [0 1]
weekday: [6 0 1 2 3 4 5]
workingday: [0 1]
weathersit: [1 2 3 4]
temp: [0.24 0.22 0.2  0.32 0.38 0.36 0.42 0.46 0.44 0.4  0.34 0.3  0.26 0.16
 0.14 0.18 0.12 0.28 0.1  0.08 0.06 0.04 0.02 0.52 0.56 0.58 0.6  0.48
 0.54 0.5  0.66 0.64 0.62 0.68 0.7  0.74 0.76 0.72 0.78 0.82 0.8  0.86
 0.88 0.9  0.84 0.92 0.94 0.96 0.98 1.  ]
atemp: [0.2879 0.2727 0.2576 0.3485 0.3939 0.3333 0.4242 0.4545 0.4394 0.4091
 0.2273 0.2121 0.197  0.1667 0.1364 0.1061 0.1212 0.1818 0.2424 0.1515
 0.3182 0.0606 0.0758 0.0909 0.303  0.0303 0.0455 0.     0.0152 0.3636
 0.5    0.5303 0.5455 0.5909 0.4697 0.5152 0.6212 0.6061 0.4848 0.3788
 0.6364 0.6515 0.6667 0.5758 0.5606 0.6818 0.697  0.7424 0.7727 0.7576
 0.7273 0.7121 0.803  0.7879 0.8333 0.8182 0.8485 0.8788 0.8636 0.8939
 0.9242 0.9091 0.9545 0.9848 1.    ]
hum: [0.81 0.8  0.75 0.86 0.76 0.77 0.72 0.82 0.88 0.87 0.94 1.   0.71 0.66
 0.57 0.46 0.42 0.39 0.44 0.47 0.5  0.43 0.4  0.35 0.3  0.32 0.64 0.69
 0.55 0.59 0.63 0.68 0.74 0.51 0.56 0.52 0.49 0.48 0.37 0.33 0.28 0.38
 0.36 0.93 0.29 0.53 0.34 0.54 0.41 0.45 0.92 0.62 0.58 0.61 0.6  0.65
 0.7  0.27 0.21 0.25 0.26 0.31 0.73 0.24 0.23 0.22 0.19 0.15 0.67 0.1
 0.08 0.12 0.14 0.13 0.17 0.16 0.18 0.96 0.2  0.85 0.   0.9  0.83 0.78
 0.84 0.89 0.79 0.97 0.91]
windspeed: [0.     0.0896 0.2537 0.2836 0.2985 0.194  0.2239 0.1343 0.1642 0.3284
 0.4478 0.3582 0.4179 0.3881 0.1045 0.4925 0.5522 0.4627 0.5224 0.5821
 0.6567 0.6119 0.7761 0.6866 0.7463 0.6418 0.806  0.8507 0.8358 0.7164]
casual: [  3   8   5   0   2   1  12  26  29  47  35  40  41  15   9   6  11   4
   7  16  20  19  10  13  14  18  17  21  33  23  22  24  28  48  52  42
  30  27  32  58  62  51  25  31  59  45  73  55  68  34  38 102  84  39
  36  72  76 108  66  60  57  53  61  90 105  98  43  46  80  83  74  37
  70  81 100  99  54  88  97 144 149 124  50  71  67  95 126 174 168 170
 175 138  92 120 145 172  44  75  94  93 110 118  64  56 111  89  69 139
 166 219 240 147 148  78  63  79 114  85 128 121 156 135 103  49  91 119
 167 181 179 161 143 182 171 180 205 197 162 142  96  65  77 178 185 184
 217 191 134 150 109 123 113  86  82 132 129 196 122 106 107 195 183 206
 158 137 173 222 187 232 204 117 164 146 125 201  87 130 216 237 221 194
 214 151 141 116 153 133 101 115 188 193 127 154 112 169 131 176 210 159
 140 157 152 136 177 215 198 248 225 242 235 224 236 160 104 234 200 155
 186 245 218 256 251 262 189 212 272 223 208 192 165 229 199 226 286 352
 357 367 291 233 264 213 202 263 265 275 243 238 190 283 295 320 355 326
 321 354 299 227 254 260 207 274 308 288 311 253 163 298 282 266 278 267
 259 281 279 220 241 230 293 257 269 255 228 276 332 361 356 331 203 258
 247 244 246 209 307 261 268 301 270 317 290 250 297 239 231 289 287 249
 284 327 325 312 350 273 302 271 362 310 294 335 347 280 292 304]
registered: [ 13  32  27  10   1   0   2   7   6  24  30  55  47  71  70  52  26  31
  25  17  16   8   4  19  46  54  73  64  67  58  43  29  20   9   5   3
  63 153  81  33  41  48  53  66 146 148 102  49  11  36  92 177  98  37
  50  79  68 202 179 110  34  87 192 109  74  65  85 186 166 127  82  40
  18  95 216 116  42  57  78  59 163 158  51  76 190 125 178  39  14  15
  56  60  90  83  69  28  35  22  12  77  44  38  75 184 174 154  97 214
  45  72 130  94 139 135 197 137 141 156 117 155 134  89  80 108  61 124
 132 196 107 100 247 140  86  62 207 210 159 151 119  93  23 171 145 101
  21 103 233 208 218 133 147  84  88 104 182 112 114 172 165 105 183 175
 170 217  91 195 152 126 115 223 123 236 128 198 157 168  99 173 121 212
 111 193 113 122 106  96 249 194 213 191 142 224 244 143 267 256 211 161
 131 246 118 164 275 120 188 227 206 181 150 136 169 242 204 230 243 238
 144 185 222 138 200 129 209 176 229 259 282 162 265 260 189 237 231 232
 199 312 271 245 221 228 239 220 268 252 205 308 283 248 303 291 280 286
 352 290 262 203 284 293 160 316 338 279 187 277 362 321 331 372 377 374
 201 398 385 309 346 402 381 272 226 215 326 441 425 320 149 254 417 251
 455 463 413 458 366 367 406 486 347 167 386 234 240 433 384 270 273 350
 472 450 435 225 464 485 323 388 266 255 415 467 456 305 470 253 235 263
 351 539 339 301 397 532 480 365 241 421 341 394 540 361 429 359 180 261
 325 521 426 298 428 487 431 288 453 454 345 289 476 269 483 274 373 302
 403 492 490 310 495 524 451 332 445 404 311 393 258 356 414 219 434 278
 285 442 484 471 488 264 281 410 516 500 343 432 475 479 355 329 400 423
 529 510 348 473 335 555 527 364 299 257 474 369 368 507 469 358 396 462
 447 412 344 439 418 514 512 340 509 436 318 499 511 496 342 324 391 466
 297 517 489 382 380 295 333 276 478 287 334 405 292 250 353 437 392 465
 313 491 409 354 493 408 378 443 460 513 497 376 328 525 296 452 506 337
 537 461 502 519 387 370 314 317 459 549 440 567 349 319 300 515 399 503
 427 306 294 444 389 501 315 449 530 536 505 371 375 534 553 438 430 383
 304 411 523 448 407 422 379 330 401 363 446 481 498 518 508 522 494 327
 504 561 543 579 551 533 554 573 545 395 547 557 623 571 614 638 628 642
 647 602 634 648 322 357 563 615 681 665 616 627 598 656 654 360 693 593
 625 599 594 542 577 639 580 620 601 661 653 645 646 419 610 677 618 595
 565 586 670 626 581 546 604 596 621 564 589 631 673 651 663 668 697 558
 619 664 649 575 613 560 617 611 420 538 662 640 659 770 608 584 307 667
 605 641 629 603 769 749 719 734 696 688 570 390 468 716 709 336 678 416
 588 674 632 457 756 746 675 742 700 643 733 680 764 679 531 637 652 778
 703 576 715 726 672 782 548 682 750 609 698 572 669 633 725 704 600 591
 535 562 757 691 622 796 730 597 658 741 790 644 740 735 739 660 712 624
 684 760 694 775 767 745 783 787 582 720 765 758 786 718 636 578 743 711
 689 751 424 699 552 768 723 810 592 811 695 744 774 736 780 762 701 692
 761 690 857 702 802 727 886 708 812 807 885 781 526 809 860 808 876 815
 818 822 707 791 833 544 789 655 806 773 737 706 566 713 800 839 779 766
 794 803 788 838 871 777 795 477 732 714 556 568 583 541 650 559 683 520
 666 585]
cnt: [ 16  40  32  13   1   2   3   8  14  36  56  84  94 106 110  93  67  35
  37  34  28  39  17   9   6  20  53  70  75  59  74  76  65  30  22  31
   5  64 154  88  44  51  61  77  72 157  52  12   4 179 100  42  57  78
  97  63  83 212 182 112  54  48  11  33 195 115  46  79  71  62  89 190
 169 132  43  19  95 219 122  45  86 172 163  69  23   7 210 134  73  50
  87 187 123  15  25  98 102  55  10  49  82  92  41  38 188  47 178 155
  24  18  27  99 217 130 136  29 128  81  68 139 137 202  60 162 144 158
 117  90 159 101 118 129  26 104  91 113 105  21  80 125 133 197 109 161
 249 143 215 185 152 126 166 120  96 103  58 116 177 184 153 108 238 222
 225 146 119 149 107 156 111 135 176 168 175 147 220 127 205 174 121 230
  66 114 216 243 199 170 165 160 140 211 145 256 223  85 206 124 255 285
 274 272 191 232 327 224 196 171 198 167 235 209 141 252 189 183 193 259
 282 261 268 142 131 214 242 148 201 150 228 204 164 233 257 151 248 194
 244 213 181 221 250 304 241 271 253 237 299 313 310 207 138 280 173 332
 331 267 301 312 278 203 279 308 226 276 336 307 273 227 239 254 287 294
 263 192 281 367 349 292 303 339 366 386 325 356 314 343 333 297 288 236
 240 452 383 284 291 309 321 337 388 300 200 180 354 361 306 277 428 362
 286 351 411 421 396 432 441 365 481 324 346 391 397 426 376 283 289 317
 420 369 359 270 353 521 499 382 449 186 528 328 234 246 444 218 412 260
 398 455 530 404 269 508 439 416 464 407 371 387 264 266 537 518 265 459
 517 544 290 410 296 440 533 520 258 450 344 553 470 298 347 373 436 378
 342 340 390 358 385 374 598 524 384 425 611 550 434 318 442 401 594 527
 364 491 295 322 456 437 392 231 394 453 604 480 565 489 487 302 547 513
 319 330 554 473 323 418 493 462 506 471 305 316 409 429 548 564 355 531
 601 405 494 478 419 399 402 341 251 229 350 311 406 495 417 454 486 467
 572 525 379 502 558 293 247 451 335 363 357 438 579 556 334 477 539 551
 424 466 326 463 380 275 315 360 476 586 423 569 538 370 498 638 607 552
 208 468 381 377 431 536 529 540 400 352 557 375 443 403 447 591 504 570
 588 320 555 492 427 461 422 414 408 457 545 496 368 245 596 563 562 372
 514 472 511 488 595 578 348 587 497 433 475 430 262 485 546 541 483 338
 543 413 435 523 532 585 584 559 582 571 516 465 329 600 609 651 519 567
 621 484 469 576 608 446 628 389 505 460 590 599 566 482 568 415 589 345
 593 393 500 479 620 625 614 395 445 512 490 515 526 509 448 560 610 522
 549 501 612 597 644 712 676 734 662 782 749 623 713 746 686 690 679 685
 648 503 721 801 750 535 729 779 649 810 957 830 657 664 684 458 581 658
 641 654 703 681 606 605 561 573 618 757 800 744 759 822 698 655 643 626
 615 617 632 646 692 704 624 656 738 671 678 660 635 616 673 781 775 677
 748 776 700 580 819 668 640 639 691 732 709 592 702 653 603 683 743 666
 813 627 706 575 769 680 717 710 622 705 630 770 659 602 733 650 873 846
 474 634 852 868 745 812 669 642 730 672 645 637 577 785 719 798 752 583
 839 796 507 693 827 694 647 665 834 850 790 724 869 793 723 534 831 613
 857 867 823 542 811 795 833 791 900 824 687 843 804 697 747 722 689 849
 872 631 674 814 633 825 629 835 667 755 794 661 772 771 777 715 847 741
 877 788 913 891 688 699 751 760 820 837 652 739 865 767 858 737 862 818
 854 682 851 848 897 832 893 815 878 740 783 707 941 736 845 864 808 870
 754 844 853 856 725 863 792 696 701 871 968 970 925 977 758 884 766 894
 842 774 797 886 892 976 805 898 967 838 953 905 899 663 727 784 809 917
 901 887 761 806 948 670 619 943 817 888 890 714 711 731 675 728 922 786
 938 826 963 708 636]

# Verifica período de cobertura do dataset

In [7]:
print("Primeira data:", df["dteday"].min())
print("Última data:", df["dteday"].max())

Primeira data: 2011-01-01
Última data: 2012-12-31

## Criação do datetime para melhor representação do momento do registro

In [8]:
df["datetime"] = pd.to_datetime(df["dteday"]) + pd.to_timedelta(df["hr"], unit="h")
df["datetime"]

0       2011-01-01 00:00:00
1       2011-01-01 01:00:00
2       2011-01-01 02:00:00
3       2011-01-01 03:00:00
4       2011-01-01 04:00:00
                ...
17374   2012-12-31 19:00:00
17375   2012-12-31 20:00:00
17376   2012-12-31 21:00:00
17377   2012-12-31 22:00:00
17378   2012-12-31 23:00:00
Name: datetime, Length: 17379, dtype: datetime64[ns]

## Verifica ordenação das datas

In [9]:
# True = ordenada
# False = desordenada
df['datetime'].is_monotonic_increasing

True

## Verifica duplicidade de datas

In [10]:
df['datetime'].duplicated().sum()

np.int64(0)

# Verifica horas faltantes

In [11]:
# Define o período esperado
expected_range = pd.date_range(start=df['datetime'].min(), end=df['datetime'].max(), freq='h')

# verifica quais valores existem em expected_range mas não existem no datetime
missing_hours = expected_range.difference(df['datetime'])

len(missing_hours)

165

In [12]:
missing_hours

DatetimeIndex(['2011-01-02 05:00:00', '2011-01-03 02:00:00',
               '2011-01-03 03:00:00', '2011-01-04 03:00:00',
               '2011-01-05 03:00:00', '2011-01-06 03:00:00',
               '2011-01-07 03:00:00', '2011-01-11 03:00:00',
               '2011-01-11 04:00:00', '2011-01-12 03:00:00',
               ...
               '2012-10-30 07:00:00', '2012-10-30 08:00:00',
               '2012-10-30 09:00:00', '2012-10-30 10:00:00',
               '2012-10-30 11:00:00', '2012-10-30 12:00:00',
               '2012-11-08 03:00:00', '2012-11-29 03:00:00',
               '2012-12-24 04:00:00', '2012-12-25 03:00:00'],
              dtype='datetime64[ns]', length=165, freq=None)

## Identifica blocos de horas faltantes

Durante a verificação da estrutura temporal, foram identificados 75 blocos de horários faltantes, totalizando 165 horas sem registros.

Para identificar essas lacunas, os timestamps existentes foram comparados com uma sequência horária contínua utilizando pd.date_range() e difference(). Os horários ausentes foram posteriormente agrupados para identificar os períodos consecutivos sem registros.

Essa etapa é importante para avaliar a continuidade da série temporal antes de iniciar a EDA

In [13]:
# Cria um dataframe com as horas faltantes
missing_df = pd.DataFrame({
    'datetime': missing_hours
})

missing_df.head()

             datetime
0 2011-01-02 05:00:00
1 2011-01-03 02:00:00
2 2011-01-03 03:00:00
3 2011-01-04 03:00:00
4 2011-01-05 03:00:00

In [14]:
# Calcula a diferença com relação ao valor anterior ao atual
missing_df['time_diff'] = missing_df['datetime'].diff()

missing_df['group'] = (
    
    # verifica se a diferença do horários atual é superior a 1 hora em relação ao horário anterior
    missing_df['time_diff'] != pd.Timedelta(hours=1)
    
).cumsum() # cria a soma acumulada
missing_df

               datetime        time_diff  group
0   2011-01-02 05:00:00              NaT      1
1   2011-01-03 02:00:00  0 days 21:00:00      2
2   2011-01-03 03:00:00  0 days 01:00:00      2
3   2011-01-04 03:00:00  1 days 00:00:00      3
4   2011-01-05 03:00:00  1 days 00:00:00      4
..                  ...              ...    ...
160 2012-10-30 12:00:00  0 days 01:00:00     71
161 2012-11-08 03:00:00  8 days 15:00:00     72
162 2012-11-29 03:00:00 21 days 00:00:00     73
163 2012-12-24 04:00:00 25 days 01:00:00     74
164 2012-12-25 03:00:00  0 days 23:00:00     75

[165 rows x 3 columns]

In [15]:
missing_periods = (
    missing_df
    .groupby('group') # resume os grupos criados de acordo com group em missing_df
    .agg(
        start_datetime=('datetime', 'min'), # inicio da período
        end_datetime=('datetime', 'max'), # fim do período
        missing_hours=('datetime', 'count') # quantidade de horas faltantes do período
    )
    .reset_index(drop=True)
)

missing_periods

        start_datetime        end_datetime  missing_hours
0  2011-01-02 05:00:00 2011-01-02 05:00:00              1
1  2011-01-03 02:00:00 2011-01-03 03:00:00              2
2  2011-01-04 03:00:00 2011-01-04 03:00:00              1
3  2011-01-05 03:00:00 2011-01-05 03:00:00              1
4  2011-01-06 03:00:00 2011-01-06 03:00:00              1
..                 ...                 ...            ...
70 2012-10-29 01:00:00 2012-10-30 12:00:00             36
71 2012-11-08 03:00:00 2012-11-08 03:00:00              1
72 2012-11-29 03:00:00 2012-11-29 03:00:00              1
73 2012-12-24 04:00:00 2012-12-24 04:00:00              1
74 2012-12-25 03:00:00 2012-12-25 03:00:00              1

[75 rows x 3 columns]

In [16]:
print('Horas faltantes: ', missing_periods['missing_hours'].sum())

Horas faltantes:  165

# Renomeando colunas

In [17]:
# Renomeia as colunas
df = df.rename(columns={
    'dteday':'date',
    'yr':'year',
    'mnth':'month',
    'hr':'hour',
    'workingday':'working_day',
    'weathersit': 'weather_sit',
    'atemp':'feeling_temp',
    'windspeed': 'wind_speed'
})

# Remove a coluna date

In [18]:
df = df.drop(columns='date', axis=1)

# Reposiciona coluna cnt para o final do dataset

In [19]:
cnt = df.pop('cnt')
df.insert(len(df.columns), 'cnt', cnt)
df.head()

,instant,season,year,month,hour,holiday,weekday,working_day,weather_sit,temp,feeling_temp,hum,wind_speed,casual,registered,datetime,cnt
0,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,2011-01-01 00:00:00,16
1,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,2011-01-01 01:00:00,40
2,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,2011-01-01 02:00:00,32
3,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,2011-01-01 03:00:00,13
4,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,2011-01-01 04:00:00,1

# Salva o dataset

In [20]:
file_name = 'bike_sharing_silver.csv'
df.to_csv(DATA_PATH+file_name, sep=',', index=None)